/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function readFileAsync(path: string): Promise<Buffer>
export function asyncPlus100(p: Promise<number>): Promise<number>
export function asyncFib(input: number): Promise<number>
export interface Agdvt {
  sgt?: string
}
export function updateAgdvt(agt: Agdvt, gh: string): Agdvt
